name: rts_demo_client
description: The client for a simple networked real-time strategy game
dependencies:
  vector_math: any
  barback: any
  analyzer: any
transformers:
- rts_demo_client/shader_loader
- rts_demo_client/model_loader
